# Generated by Django 6.0.7 on 2026-07-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionpoint',
            new_name='dashapp_act_status_f1d344_idx',
            old_name='dashapp_act_status_4bd846_idx',
        ),
        migrations.RenameIndex(
            model_name='actionpoint',
            new_name='dashapp_act_due_dat_7fccb9_idx',
            old_name='dashapp_act_due_dat_fc67f4_idx',
        ),
        migrations.RenameIndex(
            model_name='actionpoint',
            new_name='dashapp_act_week_st_2342e9_idx',
            old_name='dashapp_act_week_st_5a7ca0_idx',
        ),
        migrations.RenameIndex(
            model_name='actionpointassignment',
            new_name='dashapp_act_assigne_b487e0_idx',
            old_name='dashapp_act_assigne_5b7b26_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='dashapp_cal_start_d_d44fe4_idx',
            old_name='dashapp_cal_start_d_dca83f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='dashapp_not_recipie_c951d4_idx',
            old_name='dashapp_not_recipie_6af75f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='dashapp_not_created_584d4c_idx',
            old_name='dashapp_not_created_a1ffc4_idx',
        ),
    ]
