# Generated by Django 6.0.7 on 2026-07-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_calendarevent_visibility'),
        ('dashapp', '0002_rename_dashapp_act_status_4bd846_idx_dashapp_act_status_f1d344_idx_and_more'),
    ]

    operations = [
    ]
