# Generated by Django 6.0.7 on 2026-07-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0004_uploadeddocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uploadeddocument',
            new_name='dashapp_upl_categor_a22f30_idx',
            old_name='dashapp_upl_categor_ea844d_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadeddocument',
            new_name='dashapp_upl_visibil_fbc1a4_idx',
            old_name='dashapp_upl_visibil_ee1018_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadeddocument',
            new_name='dashapp_upl_uploade_ddc4db_idx',
            old_name='dashapp_upl_uploade_4d7e0e_idx',
        ),
    ]
