# Generated by Django 6.0.7 on 2026-07-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0005_assignment_status_notification_alert'),
        ('dashapp', '0005_rename_dashapp_upl_categor_ea844d_idx_dashapp_upl_categor_a22f30_idx_and_more'),
    ]

    operations = [
    ]
